### ISSUE TITLE
BAD_EXCESS on startAnimating

### ISSUE THREAD

**Issue by souhl** [solomidSF/YRActivityIndicator#1]
Hi,

just integrated into my project and crashes right after start in startAnimating in line 297.
Any idea? Let me know what you need additionally.

Thanks
Sascha

**Comment by solomidSF** [comment]
So what caused this issue?

**Comment by souhl** [comment]
Cause of limited time I had not much time this week to try it.
My first try didn't work... but unfortunately no time to dig deeper. Will try again the next days.
