### ISSUE TITLE
It does not work on Swift Project

### ISSUE THREAD

**Issue by mdfalcon104** [solomidSF/YRActivityIndicator#2]
I am trying to use your library but the activity indicator does not start animating. :(

Could you suggest for me? Why it is?

**Comment by solomidSF** [comment]
Hello, I'm not very familiar with swift, so I can't definetely say what's wrong. I've heard that you should generate some 'bridging header' to use objective c code in swift project, or something like that.

If you share some code I'll try to find a problem.

**Comment by solomidSF** [comment]
Closing because added to pods in (https://github.com/solomidSF/YRActivityIndicator/issues/3), which should solve this issue
