### ISSUE TITLE
Use with Cocoapods

### ISSUE THREAD

**Issue by ndmeiri** [solomidSF/YRActivityIndicator#3]
Hi! Would it be possible to have YRActivityIndicator converted for use with Cocoapods?

**Comment by solomidSF** [comment]
There are 1 class and 2 files h/m needed to add activity into your application. YRActivityIndicator only depend on UIKit, which is linked into your project by default, and it doesn't require any specific linking flags, so that is why I didn't connect cocoa pods.

**Comment by ndmeiri** [comment]
Using Cocoapods comes with other benefits besides ease of setting linking flags, etc. For example, updating to the latest YRActivityIndicator release becomes automated, which is much easier on the programmer. Also, using Cocoapods will most likely solve #2 when working in a Swift project. Just to name a couple.

**Comment by vGubriienko** [comment]
Вангую за поды)

**Comment by solomidSF** [comment]
Done
https://cocoapods.org/pods/YRActivityIndicator
